### ISSUE TITLE
dsp_bfp.h causes error when included by a C file

### ISSUE THREAD

**Issue by ThomasGmeinder** [xmos/lib_dsp#120]
The dsp_bfp.h uses "unsafe" and causes the below error when included by a C file.
This causes issues with libraries like lib_radar and any other C file that includes "dsp.h".
That should be fixed because it currently prevents lib_dsp functions to be used in C code which is a key requirement.

/Users/thomas/dev/IFX/IFX_radar_smartmic/xmos_soliC/lib_dsp/lib_dsp/api/dsp_bfp.h:60:43: error: expected ')'
void dsp_bfp_shl2( dsp_complex_t * unsafe pts, const uint32_t N,
                                          ^
/Users/thomas/dev/IFX/IFX_radar_smartmic/xmos_soliC/lib_dsp/lib_dsp/api/dsp_bfp.h:60:18: note: to match this '('
void dsp_bfp_shl2( dsp_complex_t * unsafe pts, const uint32_t N,
                 ^
In file included from ../src/get_chirps.c:9:

**Comment by oscarbailey-xmos** [comment]
Fixed https://github.com/xmos/lib_dsp/blob/4344d1a44d4fdae60073b5fa31c7d01d3a596720/lib_dsp/api/dsp_bfp.h#L11
