### ISSUE TITLE
.cproject file is broken

### ISSUE THREAD

**Issue by astew** [xmos/lib_dsp#77]
The [lib_dsp/.cproject](https://github.com/xmos/lib_dsp/blob/master/lib_dsp/.cproject) file appears to have been committed with some of the inline diff markers still in there. e.g.

```
                                    <listOptionValue builtIn="false" value="__XCC_HAVE_FLOAT__=1"/>
                                    <listOptionValue builtIn="false" value="_XSCOPE_PROBES_INCLUDE_FILE=&quot;/tmp/ccjsPcFI.h&quot;"/>
                                </option>
<<<<<<< HEAD
                                <option id="com.xmos.xc.compiler.option.include.paths.1034653062" name="com.xmos.xc.compiler.option.include.paths" superClass="com.xmos.xc.compiler.option.include.paths" valueType="includePath">
                                    <listOptionValue builtIn="false" value="&quot;${XMOS_TOOL_PATH}\target/include/xc&quot;"/>
                                    <listOptionValue builtIn="false" value="&quot;${XMOS_TOOL_PATH}\target/include&quot;"/>
                                    <listOptionValue builtIn="false" value="&quot;${XMOS_TOOL_PATH}\target/include/clang&quot;"/>
=======
                                <option id="com.xmos.xc.compiler.option.include.paths.497342305" name="com.xmos.xc.compiler.option.include.paths" superClass="com.xmos.xc.compiler.option.include.paths" valueType="includePath">
                                    <listOptionValue builtIn="false" value="&quot;${XMOS_TOOL_PATH}/target/include/xc&quot;"/>
                                    <listOptionValue builtIn="false" value="&quot;${XMOS_TOOL_PATH}/target/include&quot;"/>
                                    <listOptionValue builtIn="false" value="&quot;${XMOS_TOOL_PATH}/target/include/clang&quot;"/>
>>>>>>> 4cdfda4574e272900c222fcb31e7eeb5a4ee6712
                                    <listOptionValue builtIn="false" value="&quot;${workspace_loc:/app_filters}&quot;"/>
                                    <listOptionValue builtIn="false" value="&quot;${workspace_loc:/app_filters/src}&quot;"/>
                                </option>
```

**Comment by xross** [comment]
There are other oddities in the "synch" commit that need tidying. Other project files modified etc. https://github.com/xmos/lib_dsp/commit/22687423d3f604c24ca2a14dc3c306890fe7dd8c

Also, .build etc is checked in.

**Comment by ThomasGmeinder** [comment]
Thanks for reporting this.

I fixed this with pull request https://github.com/xmos/lib_dsp/pull/78
by changing the file back to it’s original version:

git checkout db8fe95f2671fb04c747ded84313da257cd4de22 -- .cproject

As a general rule:
Changes to .cproject files should never be committed.
Eclipse modifies these files regularly and so if they were checked in every commit would contain a bunch of changes to these eclipse metadata files.
This distracts from the manual changes in commit diffs and also causes merge issues (as shown by this issue).

.cproject and .project files have to be checked with the first commit to enable eclipse import.
But any changes afterwards should not be checked in.

In practise that means:
Eclipse will change the .cproject and .project files.
But these changes can be undone using git reset on the files (in the GUI or on command line)

**Comment by ThomasGmeinder** [comment]
.metadata has been removed in the meantime. The .metadata folder is generated by eclipse automatically during import and must not be checked in. That's why it's listed in .gitignore: https://github.com/xmos/lib_dsp/blob/master/.gitignore.
.build directories are also excluded by .gitignore

**Comment by oscarbailey-xmos** [comment]
Fixed by https://github.com/xmos/lib_dsp/pull/78
