### ISSUE TITLE
dsp_math_divide produces incorrect result for certain inputs

### ISSUE THREAD

**Issue by astew** [xmos/lib_dsp#80]
Certain combinations of inputs cause an overflow in dsp_math-divide which causes it to yield incorrect output. For example, `dsp_math_divide(0x02000000, 0x02000001, 24)` gives a result of `0`.

More generally, this will happen whenever `dividend<divisor` and  `(dividend<<32) / divisor` is greater than a certain value (which depends only on q_format). When this happens, at the line 

`r = d << q_format |
        (d2 + (1<<(31-q_format))) >> (32-q_format);`

`d2` is already very near `0xFFFFFFFF`, and the addition of `1<<(31-q_format)` causes an overflow.

This could be avoided by not adding `1<<(31-q_format)` (not rounding), or by explicitly checking whether an overflow is about to occur (i.e. `d2` is greater than some number, which depends on `q_format`).

These cases are likely to arise when, for example, computing `arctan()` of an angle that happens to be near `pi/4` (modulo pi/2)

**Comment by henkmuller** [comment]
Thanks - This is fixed on my fork - pull request outstanding

**Comment by oscarbailey-xmos** [comment]
Fix is on master
